### PR TITLE
Implement Communication specifications with comlib.py + Replace block with shapes

### PR DESCRIPTION
**Pull request by medik**

### CODE REVIEW

**Comment by medik** [comment]
Before pushing this implementation into the repo a script will be written to test the implementation.

**Comment by Alexander-Hjelm** [comment]
Looks good as of 460d38d!

**Comment by medik** [comment]
Changed to implement communication protocol version 2018/03/18

**Comment by Alexander-Hjelm** [comment]
Looks good! Approved.

**Pull request merged**
